---
title: "Group Porject- Indian Food"
author: "Ellyn Paris"
date: "2/10/2022"
output: html_document
---
```{r}
indian_food <- readr::read_csv("indian_food.csv")
```
```{r}
glimpse(indian_food)
```
## NAs treated as "-1"

```{r}
indian_food
```
```{r}
indian_food<-indian_food%>%
  na_if("-1")
naniar::miss_var_summary(indian_food)
```
```{r}
indian_food <- indian_food %>% 
  mutate(total_time = prep_time+cook_time)
```
## What I am trying to answer: 
# 1. Does it take more or less time to cook vegetarian versus non-vegetarian dishes? For each diet, vegetarian and non-vegetarian, identify which dish takes the most and least amount of total cook time, prep time, and cook time.

# 2. What course takes takes the longest time to make? What course takes the least amount of time to make? 
```{r}
indian_food
```


```{r}
indian_food %>% 
  filter(!is.na(total_time)) %>% 
  group_by(diet) %>% 
  summarize(mean_total_time = mean(total_time))
```
```{r}
v_nv <- indian_food %>% 
    filter(!is.na(total_time)) %>% 
  group_by(diet) %>% 
  summarize(mean_total_time = mean(total_time),
            min_total_time = min(total_time),
            max_total_time = max(total_time))
v_nv
```
```{r}
v_nv%>%
  pivot_longer(-diet, names_to ="time", values_to="cook_time")%>%
  ggplot(aes(x=diet, y=cook_time))+geom_boxplot()
```


```{r}
indian_food %>% 
  filter(diet == "non vegetarian") %>% 
  filter(total_time == 20)
```
```{r}
indian_food %>% 
  filter(diet == "vegetarian") %>% 
  filter(total_time == 10)
```
```{r}
indian_food %>% 
  filter(diet == "non vegetarian") %>% 
  filter(total_time == 270)
```
```{r}
indian_food %>% 
  filter(diet == "vegetarian") %>% 
  filter(total_time == 730)
```











